Repository First-Tee-Pittsburgh/notifications, pull requests merged in 2024-04, with the labels that each got.

#131 Message statuses on after send
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/icons/delivered.js
  client/src/icons/link_clicked.js
  client/src/icons/queued.js
  client/src/icons/sent.js
  client/src/icons/undelivered.js
  client/src/index.js
  client/src/pages/message.js
  server/api/knock.js
  server/api/salesforce.js
  server/index.js
Labels: feature

#136 Check Email & Secondary Email
  server/api/salesforce.js
Labels: feature

#138 Send message component
  client/src/App.css
  client/src/components/SendMessageForm.js
  client/src/pages/message.js
  server/api/salesforce.js
Labels: feature

#150 Specify how a message was sent
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/pages/message.js
  server/api/knock.js
Labels: feature

#156 New default message + coach signature
  client/src/App.js
  client/src/components/SendMessageForm.js
  server/api/knock.js
  server/api/salesforce.js
  server/index.js
Labels: feature

#162 Coaches only get emails when a text doesn't work
  client/src/components/SendMessageForm.js
  server/api/knock.js
  server/api/salesforce.js
  server/index.js
Labels: infrastructure

#164 [HOTFIX] coachSessions not working
  server/api/salesforce.js
Labels: bug
