Repository First-Tee-Pittsburgh/notifications, pull requests merged in 2024-05, with the labels that each got.

#167 Remove testing emails
  server/index.js
Labels: cleanup

#161 Daily api tests
  package-lock.json
  package.json
  server/api/knock.js
  server/test/runTests.js
  server/test/testKnock.js
  server/test/testMailersend.js
  server/test/testSalesforce.js
  server/test/testTwilio.js
Labels: testing

#169 Pulling phone number from custom form question
  client/src/index.js
  client/src/pages/message.js
  client/src/pages/monitor.js
  server/api/salesforce.js
Labels: feature
